name: nip46_event_signer
description: Nostr nip46 event signer for ndk
version: 1.0.0
repository: https://github.com/relaystr/ndk
topics:
  - nostr
  - nip46
  - remote-signer
  - event-signer
  - ndk

environment:
  sdk: ^3.8.1

dependencies:
  ndk: ^0.5.0
  nip01: ^0.3.0+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
