name: ndk_sembast
description: A Sembast cache manager and wallets repository for NDK (Nostr Development Kit), in pure Dart with web support.
version: 0.1.0
homepage: https://github.com/relaystr/ndk
repository: https://github.com/relaystr/ndk

topics:
  - nostr
  - ndk
  - sembast

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  ndk: ^0.10.1
  path: ^1.9.1
  sembast: ">=3.8.6 <4.0.0"
  sembast_web: ^2.4.6

dev_dependencies:
  lints: ^6.1.0
  ndk_cache_manager_test_suite: ^1.0.1-dev.14
  test: any
