// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiEventVerifierGreet(name: name);

Future<bool> verifySchnorrSignature(
        {required String pubKeyHex,
        required String eventIdHex,
        required String signatureHex}) =>
    RustLib.instance.api.crateApiEventVerifierVerifySchnorrSignature(
        pubKeyHex: pubKeyHex,
        eventIdHex: eventIdHex,
        signatureHex: signatureHex);
