// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Convert a keyset ID (hex string) to an integer for use in derivation path
/// Performs: BigInt.parse(keysetId, radix: 16) % (2^31 - 1)
Future<int> keysetIdToInt({required String keysetId}) =>
    RustLib.instance.api.crateApiCashuSeedKeysetIdToInt(keysetId: keysetId);

/// Generate a new BIP39 seed phrase
/// Returns a 24-word mnemonic by default (32 bytes of entropy)
Future<String> generateSeedPhrase() =>
    RustLib.instance.api.crateApiCashuSeedGenerateSeedPhrase();

/// Derive a secret and blinding factor from a BIP39 seed phrase
///
/// # Arguments
/// * `seed_phrase` - BIP39 mnemonic phrase (space-separated words)
/// * `passphrase` - Optional passphrase (use empty string if none)
/// * `counter` - Counter value for derivation
/// * `keyset_id` - Keyset ID as hex string
///
/// # Returns
/// Result containing secret_hex and blinding_hex, or an error message
Future<CashuSeedDeriveSecretResultRust> deriveSecretRust(
        {required String seedPhrase,
        required String passphrase,
        required int counter,
        required String keysetId}) =>
    RustLib.instance.api.crateApiCashuSeedDeriveSecretRust(
        seedPhrase: seedPhrase,
        passphrase: passphrase,
        counter: counter,
        keysetId: keysetId);

class CashuSeedDeriveSecretResultRust {
  final String secretHex;
  final String blindingHex;

  const CashuSeedDeriveSecretResultRust({
    required this.secretHex,
    required this.blindingHex,
  });

  @override
  int get hashCode => secretHex.hashCode ^ blindingHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CashuSeedDeriveSecretResultRust &&
          runtimeType == other.runtimeType &&
          secretHex == other.secretHex &&
          blindingHex == other.blindingHex;
}
