name: cli
on: [workflow_dispatch]
jobs:
  cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/ndk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: dart build cli
