name: Tag and start pre-release
on:
  push:
    branches: [master]

jobs:
  publish-packages:
    name: Create tags for pre-release

    permissions:
      actions: write
      contents: write
    runs-on: [ ubuntu-latest ]
    if: contains(github.event.head_commit.message, 'chore(release)')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64
      - name: Tag and start pre-release
        uses: bluefireteam/melos-action@v3
        with:
          tag: true
      - run: |
          melos exec -c 1 --no-published --no-private --order-dependents -- \
          gh workflow run prerelease-publish.yml \
          --ref \$MELOS_PACKAGE_NAME-v\$MELOS_PACKAGE_VERSION
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}