name: Start package releases
on:
  push:
    branches: [master]

jobs:
  publish-packages:
    name: Start package releases

    permissions:
      actions: write
      contents: write
    runs-on: [ ubuntu-latest ]
    if: contains(github.event.head_commit.message, 'chore(release)')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64
      - name: Setup Melos
        uses: bluefireteam/melos-action@v3
        with:
          melos-version: "8.3.0"
      - name: Publish changed packages
        run: |
          melos exec -c 1 --no-published --no-private -- \
          gh workflow run prerelease-publish.yaml \
          --ref master \
          -f package_name=\$MELOS_PACKAGE_NAME \
          -f package_version=\$MELOS_PACKAGE_VERSION \
          -f commit_sha=$GITHUB_SHA
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
